#!/bin/sh

/sbin/e-smith/check4danb35Updates -m >/dev/null 2>&1
EXITVALUE=$?
if [ $EXITVALUE != 0 ]; then
    /usr/bin/logger -t check4danb35Updates "ALERT exited abnormally with [$EXITVALUE]"
fi
exit 0
